= Terraform Azure Functions Testbed

:toc:
:toc-title: Table of Contents

== Introduction

This project aims to provision a test environment for Azure Functions using Terraform. Azure Functions is a serverless compute service provided by Microsoft Azure, allowing you to run event-triggered code without the need to explicitly provision or manage infrastructure. This testbed serves as a playground for developers and DevOps engineers to efficiently deploy and manage serverless applications in a structured Azure environment.

== Objectives

- Set up a robust test environment for Azure Functions using Terraform.
- Ensure seamless integration with Azure services like Storage Accounts and Service Plans.
- Demonstrate infrastructure as code (IaC) best practices with Terraform.

[#_first_steps]
== First Steps

=== **Clone the Repository:**

   Clone this repository to your local machine using the command:

```bash
git clone <repository_url>
```

=== **Configure Azure Provider:**

   Ensure you have configured your local environment with Azure CLI and Terraform. Set up the Azure provider by setting your subscription ID in the `variables.tf` file:

```terraform
variable "subscription_id" {
 description = "The subscription ID for the Azure provider"
 type        = string
}
```

=== **Initiate Terraform:**

   Within the project directory, initialize Terraform to install the necessary provider plugins:

```bash
terraform init
```

=== **Build Function deployment package**

    Currently, this step is not automated.

```bash
cd function/BlobUploadTrigger
zip -r ../../terraform/function_code.zip .
```

=== **Apply Terraform Configuration:**

   Apply the configuration to create the Azure resources:

```bash
terraform apply
```

   Confirm the plan to provision the resources.

=== Watch the results

When you upload a blob to the __uploadedblobs__ container, you will see invocations of the __BlobTrigger__ function.

== Documentation

Comprehensive documentation is available to assist you in managing the Azure Functions testbed:

- Terraform Configuration Files
- Azure Provider Configuration
- Best Practices in Infrastructure as Code

== Links

- Azure Functions Documentation: https://docs.microsoft.com/en-us/azure/azure-functions/
- Terraform AzureRM Provider Documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs

== Contributing

I welcome contributions from the community. Please feel free to submit a pull request or open an issue for improvements or fixes.

== License

This project is licensed under the MIT License - see the LICENSE file for details.